// <auto-generated />
namespace CafeteriaApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_photo_and_alternatetext_to_menuitem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_photo_and_alternatetext_to_menuitem));
        
        string IMigrationMetadata.Id
        {
            get { return "201703042144569_add_photo_and_alternatetext_to_menuitem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
